name: Publish

on:
  workflow_run:
    workflows: ["Run Unit Tests"]
    branches: [master]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --silent
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
